title:              SW Developer
email:              zcx5674@gmail.com
description:        I like to learn and enjoy learning new skills.
author:             Wonyon Jang
baseurl:            ""
url:                "https://zcx6263.github.io"

# Social Profiles
twitter_username:   
github_username:    zcx6263
facebook_username:  
linkedin_username: in/wonyong-jang-3250b4165/

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
