title:              SW Developer
email:              zcx6263@example.com
description:        A Blog Theme by Start Bootstrap
author:             Wonyong Jang
baseurl:            ""
url:                "https://zcx6263.github.io"

# Social Profiles
twitter_username:   
github_username:    zcx6263
facebook_username:  in/wonyong-jang-3250b4165
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
